runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /LISTener_images
  static_dir: LISTener_images

- url: .*
  script: main.app
  login: required

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: latest
